# Generated by Django 6.0.4 on 2026-06-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vagas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(choices=[('TABU', 'TABU'), ('MEG DISTRIBUIDORA', 'MEG DISTRIBUIDORA'), ('GRUPO GALACTUS DO BRASIL', 'GRUPO GALACTUS DO BRASIL')], max_length=100, verbose_name='Empresa')),
                ('tipo_vaga', models.CharField(max_length=100, verbose_name='Tipo de Vaga')),
                ('data_abertura', models.DateField(verbose_name='Data de Abertura')),
                ('data_fechamento', models.DateField(verbose_name='Data de Fechamento')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('status', models.CharField(choices=[('Aberta', 'Aberta'), ('Fechada', 'Fechada')], max_length=100, verbose_name='Status')),
            ],
        ),
    ]
