# Generated by Django 6.0.4 on 2026-06-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagas',
            name='justificativa',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa'),
        ),
        migrations.AddField(
            model_name='vagas',
            name='motivo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='vagas',
            name='nome_candidato',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Candidato'),
        ),
        migrations.AddField(
            model_name='vagas',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='vagas',
            name='previsao_admissao',
            field=models.DateField(blank=True, null=True, verbose_name='Previsão de Admissão'),
        ),
        migrations.AlterField(
            model_name='vagas',
            name='data_fechamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fechamento'),
        ),
    ]
