# Generated by Django 6.0.4 on 2026-06-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='empresa',
            field=models.CharField(choices=[('AGRO INDUSTRIAL TABU S/A', 'AGRO INDUSTRIAL TABU S/A'), ('INSOLITO HOTEL LTDA', 'INSOLITO HOTEL LTDA'), ('GALACTUS DO BRASIL', 'GALACTUS DO BRASIL'), ('TRANCOSO BIO RISORT AGROPECUARIA LTDA', 'TRANCOSO BIO RISORT AGROPECUARIA LTDA'), ('MEG DISTRIBUIDORA DE COMBUSTIVEIS LTDA', 'MEG DISTRIBUIDORA DE COMBUSTIVEIS LTDA'), ('JUBARTE CONCEITO', 'JUBARTE CONCEITO')], max_length=100, verbose_name='Empresa'),
        ),
    ]
