# Generated by Django 6.0.4 on 2026-06-15 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0003_vagas_sigiloso_vagas_consultoria_vagas_area_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vagas',
            table='vagas_rh',
        ),
    ]
