# Generated by Django 6.0.4 on 2026-06-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0004_alter_vagas_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='status',
            field=models.CharField(choices=[('Aberta', 'Aberta'), ('Fechada', 'Fechada'), ('Suspensa', 'Suspensa')], max_length=100, verbose_name='Status'),
        ),
    ]
