# Generated by Django 6.0.4 on 2026-06-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0005_alter_vagas_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='motivo',
            field=models.CharField(blank=True, choices=[('AUMENTO DE QUADRO', 'AUMENTO DE QUADRO'), ('SUBSTITUIÇÃO', 'SUBSTITUIÇÃO')], max_length=200, null=True, verbose_name='Motivo'),
        ),
    ]
