# Generated by Django 6.0.4 on 2026-07-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0006_alter_vagas_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagas',
            name='aproveitamento',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=100, null=True, verbose_name='Aproveitamento Interno'),
        ),
    ]
