# Generated by Django 6.0.4 on 2026-07-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0007_vagas_aproveitamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='tipo_vaga',
            field=models.CharField(choices=[('Tático', 'Tático'), ('Operacional', 'Operacional')], max_length=100, verbose_name='Tipo de Vaga'),
        ),
    ]
