# Generated by Django 6.0.4 on 2026-06-01 20:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrestadorPJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(help_text='Somente dígitos, 14 caracteres.', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='O CNPJ deve conter exatamente 14 dígitos numéricos (sem pontuação).', regex='^\\d{14}$')], verbose_name='CNPJ')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, verbose_name='Nome fantasia')),
                ('representante', models.CharField(blank=True, max_length=150, verbose_name='Representante')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Prestador PJ',
                'verbose_name_plural': 'Prestadores PJ',
                'ordering': ['razao_social'],
                'indexes': [models.Index(fields=['cnpj'], name='legal_perso_cnpj_b4cc21_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContratoPJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True, verbose_name='Código do contrato')),
                ('tipo', models.CharField(choices=[('DETERMINADO', 'Prazo determinado'), ('INDETERMINADO', 'Prazo indeterminado'), ('PROJETO', 'Por projeto')], max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('ENCERRADO', 'Encerrado'), ('SUSPENSO', 'Suspenso')], default='ATIVO', max_length=20, verbose_name='Status')),
                ('area', models.CharField(blank=True, max_length=120, verbose_name='Área / Departamento')),
                ('centro_custo', models.CharField(blank=True, max_length=40, verbose_name='Centro de custo')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de encerramento')),
                ('motivo_desligamento', models.CharField(blank=True, choices=[('FIM_CONTRATO', 'Término do contrato'), ('RESC_EMPRESA', 'Rescisão pela empresa'), ('RESC_PRESTADOR', 'Rescisão pelo prestador'), ('DESEMPENHO', 'Desempenho'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Motivo do desligamento')),
                ('valor_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor mensal (R$)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='legal_person.prestadorpj', verbose_name='Prestador')),
            ],
            options={
                'verbose_name': 'Contrato PJ',
                'verbose_name_plural': 'Contratos PJ',
                'ordering': ['-data_inicio'],
                'indexes': [models.Index(fields=['status'], name='legal_perso_status_50dab9_idx'), models.Index(fields=['data_inicio'], name='legal_perso_data_in_7fefee_idx'), models.Index(fields=['data_fim'], name='legal_perso_data_fi_4143c5_idx')],
            },
        ),
    ]
