# Generated by Django 6.0.4 on 2026-06-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=200, verbose_name='Nome da empresa')),
                ('matricula', models.CharField(max_length=50, unique=True, verbose_name='Matrícula')),
                ('nome_funcionario', models.CharField(max_length=150, verbose_name='Nome do funcionário')),
                ('setor', models.CharField(max_length=120, verbose_name='Setor')),
                ('data_admissao', models.DateField(verbose_name='Data de admissão')),
                ('data_demissao', models.DateField(blank=True, null=True, verbose_name='Data de demissão')),
            ],
            options={
                'verbose_name': 'Prestador',
                'verbose_name_plural': 'Prestadores',
                'ordering': ['nome_empresa', 'nome_funcionario'],
            },
        ),
        migrations.RemoveIndex(
            model_name='contratopj',
            name='legal_perso_status_50dab9_idx',
        ),
        migrations.RemoveIndex(
            model_name='contratopj',
            name='legal_perso_data_in_7fefee_idx',
        ),
        migrations.RemoveIndex(
            model_name='contratopj',
            name='legal_perso_data_fi_4143c5_idx',
        ),
        migrations.RemoveIndex(
            model_name='prestadorpj',
            name='legal_perso_cnpj_b4cc21_idx',
        ),
        migrations.DeleteModel(
            name='ContratoPJ',
        ),
        migrations.DeleteModel(
            name='PrestadorPJ',
        ),
    ]
