# Generated by Django 6.0.4 on 2026-06-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_person', '0002_prestador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestador',
            name='nome_empresa',
            field=models.CharField(choices=[('TABU', 'TABU'), ('MEG DISTRIBUIDORA', 'MEG DISTRIBUIDORA'), ('GRUPO GALACTUS DO BRASIL', 'GRUPO GALACTUS DO BRASIL')], max_length=200, verbose_name='Nome da empresa'),
        ),
    ]
