# Generated by Django 6.0.4 on 2026-06-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_empresa', models.CharField(choices=[('AGRO INDUSTRIAL TABU S/A', 'AGRO INDUSTRIAL TABU S/A'), ('INSOLITO HOTEL LTDA', 'INSOLITO HOTEL LTDA'), ('GALACTUS DO BRASIL', 'GALACTUS DO BRASIL'), ('TRANCOSO BIO RISORT AGROPECUARIA LTDA', 'TRANCOSO BIO RISORT AGROPECUARIA LTDA'), ('MEG DISTRIBUIDORA DE COMBUSTIVEIS LTDA', 'MEG DISTRIBUIDORA DE COMBUSTIVEIS LTDA'), ('JUBARTE CONCEITO', 'JUBARTE CONCEITO')], default='', max_length=40, verbose_name='Nome da empresa')),
                ('matricula', models.IntegerField(default=0, verbose_name='Matrícula')),
                ('nom_funcionario', models.CharField(default='', max_length=60, verbose_name='Nome do funcionário')),
                ('setor', models.CharField(default='', max_length=60, verbose_name='Setor')),
                ('dat_afast_func_acidte', models.DateField(blank=True, null=True, verbose_name='Data de afastamento')),
            ],
            options={
                'db_table': 'cat',
            },
        ),
    ]
