# Generated by Django 6.0.4 on 2026-06-04 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('cod_empresa', models.IntegerField(db_column='cod_empresa', primary_key=True, serialize=False, verbose_name='Código da empresa')),
                ('nom_abrev', models.CharField(db_column='nom_abrev', max_length=40, verbose_name='Nome abreviado')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresa',
                'ordering': ['cod_empresa'],
            },
        ),
        migrations.CreateModel(
            name='UnidadeLotacao',
            fields=[
                ('cod_unid_lotac', models.CharField(db_column='cod_unid_lotac', max_length=20, primary_key=True, serialize=False, verbose_name='Código da unidade de lotação')),
                ('des_unid_lotac', models.CharField(db_column='des_unid_lotac', max_length=60, verbose_name='Descrição (setor)')),
            ],
            options={
                'verbose_name': 'Unidade de lotação',
                'verbose_name_plural': 'Unidades de lotação',
                'db_table': 'unid_lotac',
                'ordering': ['cod_unid_lotac'],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdn_funcionario', models.IntegerField(db_column='cdn_funcionario', verbose_name='Matrícula')),
                ('nom_pessoa_fisic', models.CharField(db_column='nom_pessoa_fisic', max_length=60, verbose_name='Nome do funcionário')),
                ('empresa', models.ForeignKey(db_column='cdn_empresa', on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='cat.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'db_table': 'funcionario',
                'ordering': ['empresa', 'cdn_funcionario'],
            },
        ),
        migrations.CreateModel(
            name='CAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat_afast_func_acidte', models.DateField(db_column='dat_afast_func_acidte', verbose_name='Data do afastamento')),
                ('empresa', models.ForeignKey(db_column='cdn_empresa', on_delete=django.db.models.deletion.PROTECT, related_name='cats', to='cat.empresa', verbose_name='Empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cats', to='cat.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'CAT',
                'verbose_name_plural': 'CATs',
                'db_table': 'cat',
                'ordering': ['-dat_afast_func_acidte'],
            },
        ),
        migrations.CreateModel(
            name='FuncUnidLotacPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat_inic_lotac_func', models.DateField(db_column='dat_inic_lotac_func', verbose_name='Início da lotação')),
                ('dat_fim_lotac_func', models.DateField(blank=True, db_column='dat_fim_lotac_func', null=True, verbose_name='Fim da lotação')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotacoes', to='cat.funcionario', verbose_name='Funcionário')),
                ('unid_lotac', models.ForeignKey(db_column='cod_unid_lotac', on_delete=django.db.models.deletion.PROTECT, related_name='lotacoes', to='cat.unidadelotacao', verbose_name='Unidade de lotação')),
            ],
            options={
                'verbose_name': 'Lotação do funcionário',
                'verbose_name_plural': 'Lotações do funcionário',
                'db_table': 'func_unid_lotac_plano',
                'ordering': ['funcionario', '-dat_inic_lotac_func'],
            },
        ),
        migrations.AddIndex(
            model_name='funcionario',
            index=models.Index(fields=['empresa', 'cdn_funcionario'], name='funcionario_cdn_emp_08fb32_idx'),
        ),
        migrations.AddConstraint(
            model_name='funcionario',
            constraint=models.UniqueConstraint(fields=('empresa', 'cdn_funcionario'), name='uq_funcionario_empresa_matricula'),
        ),
        migrations.AddIndex(
            model_name='cat',
            index=models.Index(fields=['dat_afast_func_acidte'], name='cat_dat_afa_796e0c_idx'),
        ),
        migrations.AddIndex(
            model_name='cat',
            index=models.Index(fields=['empresa', 'funcionario'], name='cat_cdn_emp_7cc34b_idx'),
        ),
        migrations.AddIndex(
            model_name='funcunidlotacplano',
            index=models.Index(fields=['funcionario', 'dat_inic_lotac_func'], name='func_unid_l_funcion_01d809_idx'),
        ),
    ]
