# Generated by Django 6.0.4 on 2026-06-04 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='funcunidlotacplano',
            name='func_unid_l_funcion_01d809_idx',
        ),
        migrations.AlterModelOptions(
            name='cat',
            options={},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='unidadelotacao',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='funcionario',
            name='uq_funcionario_empresa_matricula',
        ),
        migrations.RemoveIndex(
            model_name='cat',
            name='cat_dat_afa_796e0c_idx',
        ),
        migrations.RemoveIndex(
            model_name='cat',
            name='cat_cdn_emp_7cc34b_idx',
        ),
        migrations.RemoveIndex(
            model_name='funcionario',
            name='funcionario_cdn_emp_08fb32_idx',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='unid_lotac',
            field=models.ForeignKey(blank=True, db_column='cod_unid_lotac', null=True, on_delete=django.db.models.deletion.PROTECT, to='cat.unidadelotacao'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='dat_afast_func_acidte',
            field=models.DateField(db_column='dat_afast_func_acidte'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cat.funcionario'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cod_empresa',
            field=models.IntegerField(db_column='cod_empresa', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nom_abrev',
            field=models.CharField(db_column='nom_abrev', max_length=40),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cdn_funcionario',
            field=models.IntegerField(db_column='cdn_funcionario'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='empresa',
            field=models.ForeignKey(db_column='cdn_empresa', on_delete=django.db.models.deletion.PROTECT, to='cat.empresa'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nom_pessoa_fisic',
            field=models.CharField(db_column='nom_pessoa_fisic', max_length=60),
        ),
        migrations.AlterField(
            model_name='unidadelotacao',
            name='cod_unid_lotac',
            field=models.CharField(db_column='cod_unid_lotac', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unidadelotacao',
            name='des_unid_lotac',
            field=models.CharField(db_column='des_unid_lotac', max_length=60),
        ),
        migrations.RemoveField(
            model_name='cat',
            name='empresa',
        ),
        migrations.DeleteModel(
            name='FuncUnidLotacPlano',
        ),
    ]
