# Generated by Django 6.0.4 on 2026-06-15 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0002_alter_cat_dat_afast_func_acidte'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cat',
            table='cat_rh',
        ),
    ]
