# Generated by Django 5.2.15 on 2026-06-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0002_remove_funcunidlotacplano_func_unid_l_funcion_01d809_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='unid_lotac',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='funcionario',
        ),
        migrations.AddField(
            model_name='cat',
            name='matricula',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cat',
            name='nom_empresa',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='cat',
            name='nom_funcionario',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='cat',
            name='setor',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='cat',
            name='dat_afast_func_acidte',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='UnidadeLotacao',
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
