# Generated by Django 5.2.15 on 2026-06-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0003_remove_funcionario_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='dat_afast_func_acidte',
            field=models.DateField(blank=True, null=True, verbose_name='Data de afastamento'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='matricula',
            field=models.IntegerField(default=0, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='nom_empresa',
            field=models.CharField(default='', max_length=40, verbose_name='Nome da empresa'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='nom_funcionario',
            field=models.CharField(default='', max_length=60, verbose_name='Nome do funcionário'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='setor',
            field=models.CharField(default='', max_length=60, verbose_name='Setor'),
        ),
    ]
