# Generated by Django 6.0.4 on 2026-06-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0003_alter_cat_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='acidente',
            field=models.CharField(default='', max_length=100, verbose_name='Acidente'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='dat_afast_func_acidte',
            field=models.DateField(default=None, verbose_name='Data do acidente'),
        ),
    ]
