# Generated by Django 6.0.4 on 2026-06-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0004_alter_cat_dat_afast_func_acidte_alter_cat_matricula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='nom_empresa',
            field=models.CharField(choices=[('TABU', 'TABU'), ('MEG DISTRIBUIDORA', 'MEG DISTRIBUIDORA'), ('GRUPO GALACTUS DO BRASIL', 'GRUPO GALACTUS DO BRASIL')], default='', max_length=40, verbose_name='Nome da empresa'),
        ),
    ]
