# Generated by Django 6.0.4 on 2026-07-27 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0004_cat_acidente_alter_cat_dat_afast_func_acidte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='matricula',
        ),
    ]
