# Generated by Django 6.0.4 on 2026-06-12 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pj_rh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestador',
            name='matricula',
        ),
    ]
