# Generated by Django 6.0.4 on 2026-06-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj_rh', '0002_remove_prestador_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestador',
            name='cargo',
            field=models.CharField(default='', max_length=120, verbose_name='Cargo'),
        ),
    ]
