# Generated by Django 6.0.4 on 2026-06-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100, verbose_name='Área')),
                ('treinamento', models.CharField(max_length=100, verbose_name='Treinamento')),
                ('participante', models.IntegerField(verbose_name='Participante')),
                ('carga_horaria', models.IntegerField(verbose_name='Carga Horária')),
                ('programado', models.BooleanField(default=False, verbose_name='Programado')),
                ('realizado', models.BooleanField(default=False, verbose_name='Realizado')),
                ('reprogramado', models.BooleanField(default=False, verbose_name='Reprogramado')),
                ('cancelado', models.BooleanField(default=False, verbose_name='Cancelado')),
                ('nenhuma_alternativa', models.BooleanField(default=False, verbose_name='Nenhuma Alternativa')),
                ('sem_data_prevista', models.BooleanField(default=False, verbose_name='Sem Data Prevista')),
                ('nao_realizado', models.BooleanField(default=False, verbose_name='Não Realizado')),
            ],
        ),
    ]
