# Generated by Django 6.0.4 on 2026-06-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('treinamento', models.CharField(max_length=100)),
                ('participante', models.IntegerField()),
                ('carga_horaria', models.IntegerField()),
                ('programado', models.BooleanField(default=False)),
                ('realizado', models.BooleanField(default=False)),
                ('reprogramado', models.BooleanField(default=False)),
                ('cancelado', models.BooleanField(default=False)),
                ('nenhuma_alternativa', models.BooleanField(default=False)),
                ('sem_data_prevista', models.BooleanField(default=False)),
                ('nao_realizado', models.BooleanField(default=False)),
            ],
        ),
    ]
