# Generated by Django 6.0.4 on 2026-06-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinamento',
            name='area',
            field=models.CharField(max_length=100, verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='treinamento',
            name='cancelado',
            field=models.BooleanField(default=False, verbose_name='Cancelado'),
        ),
        migrations.AlterField(
            model_name='treinamento',
            name='carga_horaria',
            field=models.IntegerField(verbose_name='Carga Horária'),
        ),
        migrations.AlterField(
            model_name='treinamento',
            name='nao_realizado',
            field=models.BooleanField(default=False, verbose_name='Não Realizado'),
        ),
        migrations.AlterField(
            model_name='treinamento',
            name='nenhuma_alternativa',
            field=models.BooleanField(default=False, verbose_name='Nenhuma Alternativa'),
        ),
        migrations.AlterField(
            model_name='treinamento',
            name='participante',
            field=models.IntegerField(verbose_name='Participante'),
        ),
        migrations.AlterField(
            model_name='treinamento',
            name='programado',
            field=models.BooleanField(default=False, verbose_name='Programado'),
        ),
        migrations.AlterField(
            model_name='treinamento',
            name='realizado',
            field=models.BooleanField(default=False, verbose_name='Realizado'),
        ),
        migrations.AlterField(
            model_name='treinamento',
            name='reprogramado',
            field=models.BooleanField(default=False, verbose_name='Reprogramado'),
        ),
        migrations.AlterField(
            model_name='treinamento',
            name='sem_data_prevista',
            field=models.BooleanField(default=False, verbose_name='Sem Data Prevista'),
        ),
        migrations.AlterField(
            model_name='treinamento',
            name='treinamento',
            field=models.CharField(max_length=100, verbose_name='Treinamento'),
        ),
    ]
