# Generated by Django 6.0.4 on 2026-06-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinamento',
            name='participante',
            field=models.CharField(max_length=100, verbose_name='Participante'),
        ),
    ]
