# Generated by Django 6.0.4 on 2026-06-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0002_alter_treinamento_participante'),
    ]

    operations = [
        migrations.AddField(
            model_name='treinamento',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fim'),
        ),
        migrations.AddField(
            model_name='treinamento',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
    ]
