# Generated by Django 6.0.4 on 2026-06-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0003_treinamento_data_fim_treinamento_data_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='treinamento',
            name='data_fim_planejada',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fim Planejada'),
        ),
    ]
