# Generated by Django 6.0.4 on 2026-06-15 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0004_treinamento_data_fim_planejada'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='treinamento',
            table='treinamento_rh',
        ),
    ]
