# Generated by Django 6.0.4 on 2026-06-18 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0005_alter_treinamento_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treinamento',
            old_name='data_fim',
            new_name='data_realizada',
        ),
    ]
