# Generated by Django 6.0.4 on 2026-06-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0006_rename_data_fim_to_data_realizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinamento',
            name='data_realizada',
            field=models.DateField(blank=True, null=True, verbose_name='Data Realizada'),
        ),
    ]
